### ISSUE TITLE
Tracing Configuration

### ISSUE THREAD

**Issue by nsathyan-aus** [aws-observability/terraform-aws-observability-accelerator#131]
Is there any documentation on how to configure for Tracing endpoint of Otel collector? I have configured my services to export traces to Otel collector.

Tracing endpoint is configured as follows
http://adot-collector.adot-collector-kubeprometheus.svc.cluster.local:4317

```
services.AddOpenTelemetry().WithTracing(builder => builder
                    .SetResourceBuilder(ResourceBuilder.CreateDefault()
                    .AddService("ODD"))
                    .AddAspNetCoreInstrumentation()
                    .AddHttpClientInstrumentation()
                    .AddConsoleExporter()
                    .AddOtlpExporter(o =>
                    {
                        o.Endpoint = endpoint;
                    }));
```

otel is configured with tracing_enabled = true
```
Data
====
collector.yaml:
----
receivers:

  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
```

I am not seeing any traces in X-Ray and log files does not show anything related to tracing either. Is there any way to debug if Otel collector is receiving any traces from my application? I have configured Console exporter and seeing traces in the console but not through otel-collector.

Any info would be great.
