### ISSUE TITLE
LogLevel value should be set from values.yml of the helm chart

### ISSUE THREAD

**Issue by nsathyan-aus** [aws-observability/terraform-aws-observability-accelerator#160]
```
  logging:
    loglevel: warn
extensions:
  sigv4auth:
    region: us-east-1
    service: aps
  health_check:
  pprof:
    endpoint: :1888
  zpages:
    endpoint: :55679
processors:
  batch/metrics:
    timeout: 30s
    send_batch_size: 500
```
It will be nice if we can set the loglevel of the otel config via helm chart variable.
