### ISSUE TITLE
[FEATURE] Use of configMapRef into GrafanaDashboard 

### ISSUE THREAD

**Issue by rlanore** [aws-observability/terraform-aws-observability-accelerator#246]
#### Is your feature request related to a problem? 

Our json dashbaord is not available from web server. I want to use **configMapRef** like:

```yaml
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDashboard
metadata:
  name: kafka-dashboard
  namespace: grafana-operator
spec:
  folder: Kafka
  instanceSelector:
    matchLabels:
      dashboards: "external-grafana"
  configMapRef:
    name: grafana-kafka-dashboard
    key: json
```

#### Describe the solution you'd like

**configMapRef** is not available into grafana-operator 5.0.0-rc3.

Upgrade it to 5.5.2 will work after a merge request has been accepted into aws-observability [here](https://github.com/aws-observability/aws-observability-accelerator/pull/36)
